version: '3.1'
services:
  db:
    build: ./postgres/
    environment:
      - POSTGRES_PASSWORD="Sup3rSecr3tPassw0rd"
      - PULP_DB="pulp"
      - PULP_DB_USER="pulp"
      - PULP_DB_PASS="Ch4ng3_ThIs_P4sSW0rd"
#    volumes:
#      - ./data/postrgres/var/lib/postgresql:/var/lib/postgresql
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  qpid:
    build: ./qpidd/
  rabbitmq:
    image: rabbitmq:3-management
#    volumes:
#      - ./data/rabbitmq/var/lib/rabbitmq:/var/lib/rabbitmq
    ports:
      - "8081:15672" #Management WebUI on remote 8081 for RabbitMQ: guest/guest
  pulp3:
    build: ./pulp3/
    volumes:
#      - ./data/pulp/etc/pki/pulp:/etc/pki/pulp
      - ./data/pulp/var/lib/pulp:/var/lib/pulp
      - ./data/pulp/var/cache/pulp:/var/cache/pulp
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
    environment:
      - PULP_DB_USER="pulp"
      - PULP_DB_PASS="Ch4ng3_ThIs_P4sSW0rd"
      - PULP_DB_NAME="pulp"
      - PULP_DB_HOST="db" # Name reference resolved by docker
      - PULP_DB_PORT="5432"
